apiVersion: ndb.nutanix.com/v1alpha1
kind: Database
metadata:
  name: db
spec:
  ndbRef: "Name of the NDBServer Resource"
  databaseInstance:
    clusterId: "Nutanix Cluster Id"
    databaseInstanceName: "Database Instance Name"
    description: "Database Description"
    databaseNames:
      - database_one
      - database_two
      - database_three
    credentialSecret: db-instance-secret-name
    size: 10
    timezone: "UTC"
    type: postgres
    profiles:
      compute:
        name: ""
        id: ""
      # A Software profile is a mandatory input for proprietary (closed-source) engines such as SQL Server & Oracle
      software:
        name: ""
        id: ""
      network:
        name: ""
        id: ""
      dbParam:
        name: ""
        id: ""
      dbParamInstance:
        name: ""
        id: ""
    timeMachine:
      sla : "NAME OF THE SLA"
      dailySnapshotTime:   "12:34:56"   # Time for daily snapshot in hh:mm:ss format
      snapshotsPerDay:     4            # Number of snapshots per day
      logCatchUpFrequency: 90           # Frequency (in minutes)
      weeklySnapshotDay:   "WEDNESDAY"  # Day of the week for weekly snapshot
      monthlySnapshotDay:  24           # Day of the month for monthly snapshot
      quarterlySnapshotMonth: "Jan"     # Start month of the quarterly snapshot
